### ISSUE TITLE
能够连接生产环境的Server(Ubuntu 14.04),可是断断续续的.

### ISSUE THREAD

**Issue by gavin-k** [luofei614/SocketLog#17]
工具很好用,在开发环境上运行正常.没有出现过问题.但是:
生产环境下,一直都会有,
New Connection
Connection closed
一直循环,链接一直中断.
是不是 和服务器的配置有关系呢?还是网络的原因?

**Comment by luofei614** [comment]
这是一个已知bug，还没有修复，如果出现这种情况，把浏览器进程杀死再重启就好了。

**Comment by gavin-k** [comment]
好的,谢谢.现在已经可以用了.就是不太稳定而已.时好时坏的.得看运气.

**Comment by luofei614** [comment]
出现这个情况是因为：  你点开了 火箭图标， 点击了 保存按钮 ，  点击保存按钮后 会出现这个bug ， 但不影响正常接收日志 ， 这个bug  我最近找时间看看， 修复好了告诉你。
