### ISSUE TITLE
难道不支持window环境？

### ISSUE THREAD

**Issue by mikkyxu** [luofei614/SocketLog#7]
配置了半天，把php5.2升级到了5.4，消除所有报错之后，chrome控制台没有任何输出，唉，好无奈，是不支持windows 环境么？

**Comment by jhasheng** [comment]
内存消耗计算有误，应该是运行后减运行前
number_format((memory_get_usage() - self::$start_memory) / 1024, 2);

**Comment by luofei614** [comment]
@jhasheng   感谢反馈， 我检查一下。
