### ISSUE TITLE
接管报错 registerErrorHandler修改建议

### ISSUE THREAD

**Issue by jhasheng** [luofei614/SocketLog#9]
set_error_handler(array(
            'SoctetLog',
            'error_handler'
        ));
        register_shutdown_function(array(
            'SoctetLog',
            'fatalError'
        ));

‘SoctetLog’建议使用“__CLASS__“代替，否
![1](https://cloud.githubusercontent.com/assets/3609682/5734935/a1716cba-9bf8-11e4-8960-1c0d6f7a559c.png)
则在php5.3中使用命名空间时会提示找不到此类

**Comment by luofei614** [comment]
好的

**Comment by luofei614** [comment]
已经修改了，欢迎多提宝贵建议。
